### ISSUE TITLE
question

### ISSUE THREAD

**Issue by gsanc018** [0rtis/dfk#12]
Is there a way to search thru the entire hero catalog?

**Comment by gasse4life** [comment]
same kind for me, im looking fot the list of  liquidity_pool_id
![image](https://user-images.githubusercontent.com/18745913/157036588-866362cf-bc61-4ad0-8de1-fe036e89ea8f.png)

**Comment by 0rtis** [comment]
https://github.com/0rtis/dfk/blob/master/dex_example.py#L27
Pool id are the index of the array
